### ISSUE TITLE
Amazing !

### ISSUE THREAD

**Issue by zcdliuwei** [Tw1ddle/geometrize-functional-tests#1]
What an interesting show, I really admire your work. I am very interested in this kind of image geometric deformation effect, I would like to ask, this project can only be tested online through the browser, can I batch test and export my local images through Python script ?

**Comment by Tw1ddle** [comment]
Hi, thanks! It would be possible to use the desktop Geometrize application for this by passing it a ChaiScript script at the command line. Unfortunately it does not have a Python interface, it only accepts ChaiScript scripts.

However, I have a Twitter bot written in Python that uses it, which you could use as a reference for calling it from Python: https://github.com/Tw1ddle/geometrize-twitter-bot/blob/master/bot/geometrize.py

A stable Windows binary is here: https://github.com/Tw1ddle/geometrize/releases/download/v1.0.1/geometrize_1.0.1_windows.exe

Hope that helps!
